services:
  mysql_db_python_single:
    image: mysql:8.0
    container_name: mysql_db_python_single
    environment:
      MYSQL_ROOT_PASSWORD: mipassword
      MYSQL_DATABASE: crud_python
      MYSQL_USER: usuario             
      MYSQL_PASSWORD: mipassword 
    command: --port=3310   
    ports:
      - "3310:3310"
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d 
      - db_python_app_single:/var/lib/mysql 

  python_app_single:
    image: dockerdepruebas/dockerpython-python_app_single
    container_name: python_app_single
    ports:
      - "5601:5600"
    environment:
      MYSQL_URL: jdbc:mysql://mysql_db_python_single:3310/crud_python?autoReconnect=true&useSSL=false
      MYSQL_USER: usuario
      MYSQL_PASS: mipassword
    depends_on:
      - mysql_db_python_single

volumes:
  db_python_app_single: