services:
  db:
    image: mysql:8.0 # Using a recent stable version of MySQL
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mipassword
      MYSQL_DATABASE: crud_python
      MYSQL_USER: usuario             
      MYSQL_PASSWORD: mipassword 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d 
      - db_python_app:/var/lib/mysql # Persistent storage for MySQL data

  web:
    # Build the tomcat image from the Dockerfile in the current directory
    build: 
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: python_app
    ports:
      - "5600:5600"
    environment:
      # Use 'db' as the hostname, which is resolved by Docker's internal DNS
      MYSQL_URL: jdbc:mysql://db:3306/crud_python?autoReconnect=true&useSSL=false
      MYSQL_USER: usuario
      MYSQL_PASS: mipassword
    depends_on:
      - db

volumes:
  db_python_app: