services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mipassword
      MYSQL_DATABASE: crud_python
      MYSQL_USER: usuario             
      MYSQL_PASSWORD: mipassword 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d 
      - db_persitence:/var/lib/mysql 

  web_python:
    build: 
      context: ./dockerpython
      dockerfile: Dockerfile
      no_cache: true
    container_name: python_app
    ports:
      - "5600:5600"
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/crud_python?autoReconnect=true&useSSL=false
      MYSQL_USER: usuario
      MYSQL_PASS: mipassword
    depends_on:
      - db

  web_php:
    build: 
      context: ./dockerphp
      dockerfile: Dockerfile
      no_cache: true
    container_name: php_app
    ports:
      - "80:80"
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/crud?autoReconnect=true&useSSL=false
      MYSQL_USER: usuario
      MYSQL_PASS: mipassword
    depends_on:
      - db

  web_java:
    build: 
      context: ./dockerjava
      dockerfile: Dockerfile
      no_cache: true
    container_name: tomcat_app
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/productosdb?autoReconnect=true&useSSL=false
      MYSQL_USER: usuario
      MYSQL_PASS: mipassword
    depends_on:
      - db
  
  web_golang:
    build: 
      context: ./aplicacionGolang
      dockerfile: Dockerfile
      no_cache: true
    container_name: web_golang
    ports:
      - "8090:8090"
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/gocrud_app?autoReconnect=true&useSSL=false
      MYSQL_USER: usuario
      MYSQL_PASS: mipassword
    depends_on:
      - db
  

volumes:
  db_persitence: {}
  