services:
  mysql_db_python:
    image: mysql:8.0
    container_name: mysql_db_python
    environment:
      MYSQL_ROOT_PASSWORD: mipassword
      MYSQL_DATABASE: crud_python
      MYSQL_USER: usuario             
      MYSQL_PASSWORD: mipassword 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d 
      - db_python_app_single:/var/lib/mysql # Persistent storage for MySQL data

  web:
    build: 
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: python_app
    ports:
      - "5600:5600"
    environment:
      MYSQL_URL: jdbc:mysql://mysql_db_python:3306/crud_python?autoReconnect=true&useSSL=false
      MYSQL_USER: usuario
      MYSQL_PASS: mipassword
    depends_on:
      - mysql_db_python

volumes:
  db_python_app_single: