services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: mipassword
      MYSQL_DATABASE: productosdb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: mipassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d  
      - db_data:/var/lib/mysql

volumes:
  db_data:
  