services:
  mysql_db_php:
    image: mysql:8.0 
    container_name: mysql_db_php
    environment:
      MYSQL_ROOT_PASSWORD: mipassword
      MYSQL_DATABASE: crud
      MYSQL_USER: usuario             
      MYSQL_PASSWORD: mipassword 
    command: --port=3308   
    ports:
      - "3308:3308"
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d 
      - db_data_php:/var/lib/mysql 

  web:
    build: 
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: php_app
    ports:
      - "81:80"
    environment:
      MYSQL_URL: jdbc:mysql://mysql_db_php:3308/crud?autoReconnect=true&useSSL=false
      MYSQL_USER: usuario
      MYSQL_PASS: mipassword
    depends_on:
      - mysql_db_php

volumes:
  db_data_php: