services:
  mysql_db_tomcat:
    image: mysql:8.0 # Using a recent stable version of MySQL
    container_name: mysql_db_tomcat
    environment:
      MYSQL_ROOT_PASSWORD: mipassword
      MYSQL_DATABASE: productosdb
      MYSQL_USER: usuario             
      MYSQL_PASSWORD: mipassword 
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d 
      - db_data_tomcat:/var/lib/mysql # Persistent storage for MySQL data

  tomcat_app_simple:
    # Build the tomcat image from the Dockerfile in the current directory
    build: 
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: tomcat_app_simple
    ports:
      - "8081:8080"
    environment:
      MYSQL_URL: jdbc:mysql://mysql_db_tomcat:3307/productosdb?autoReconnect=true&useSSL=false
      MYSQL_USER: usuario
      MYSQL_PASS: mipassword
    depends_on:
      - mysql_db_tomcat

volumes:
  db_data_tomcat: