services:
  mysql_db_php:
    image: mysql:8.0 
    container_name: mysql_db_php
    environment:
      MYSQL_ROOT_PASSWORD: mipassword
      MYSQL_DATABASE: crud
      MYSQL_USER: usuario             
      MYSQL_PASSWORD: mipassword 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d 
      - db_data_php:/var/lib/mysql 

  php_app_simple:
    image: dockerdepruebas/dockerphp-web
    container_name: php_app_simple
    ports:
      - "80:80"
    environment:
      # Use 'db' as the hostname, which is resolved by Docker's internal DNS
      MYSQL_URL: jdbc:mysql://mysql_db_php:3306/crud?autoReconnect=true&useSSL=false
      MYSQL_USER: usuario
      MYSQL_PASS: mipassword
    depends_on:
      - mysql_db_php

volumes:
  db_data_php: